import type { Metadata } from "next";
import "./globals.css";
import Header from "@/widgets/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-gradient-to-b from-primary to-secondary h-screen">
        <Header />
        {children}
      </body>
    </html>
  );
}
